const express = require("express");
const protect = require("../middleware/auth.middleware");
const authorize = require("../middleware/role.middleware");
const validate = require("../middleware/validation.middleware");
const { registerValidation } = require("../validations/auth.validation");
const c = require("../controllers/admin.controller");
const router = express.Router();
router.use(protect, authorize("admin"));
router.get("/dashboard", c.getDashboard);
router.get("/agents", c.getAgents);
router.post("/agents", validate(registerValidation), c.createAgent);
router.patch("/agents/:id", c.updateAgent);
router.get("/categories", c.getCategories);
router.post("/categories", c.createCategory);
router.delete("/categories/:id", c.deleteCategory);
router.patch("/users/:id/role", c.updateUserRole);
router.patch("/users/:id/status", c.setUserStatus);
router.get("/activity-logs", c.getActivityLogs);
module.exports = router;
